/**:
  ros__parameters:
    initial_reset: true
    enable_infra1: false
    enable_infra2: false
    enable_color: true
    enable_depth: false
    enable_gyro: false
    enable_accel: false

    rgb_camera.color_profile: "640x480x30"
    depth_module.depth_profile: "640x480x30"
    align_depth.enable: false

    depth_module.emitter_enabled: 0

    rgb_camera.enable_auto_exposure: true
    rgb_camera.exposure: 100
    rgb_camera.gain: 16
    rgb_camera.enable_auto_white_balance: true

    publish_tf: true
    tf_publish_rate: 20.0